### ISSUE TITLE
Saga should return generator

### ISSUE THREAD

**Issue by dvolland** [appfoundry/react-native-multi-language-sample#1]
Thanks for the nice tutorial. Very useful!

I think I found a minor bug. The saga should be a generator function (otherwise it throws some kind of type error):

```
export function updateLanguage(action) {
  const {language} = action
  I18n.locale = language
}
```

should be 

```
export function* updateLanguage(action) {
  const {language} = action
  I18n.locale = language
}
```

**Comment by FDMatthias** [comment]
You are correct, it should be a generator function indeed. I will fix it right away, thanks for bringing this to our attention!

**Comment by bartvandeweerdt** [comment]
👍

**Comment by sseyha** [comment]
Hi, Thank so much for the update and tutorial.
But could anyone help me about the change language?
It's working fine, but it's could not change the navigation bar title.
Anyone have solution about this, pls...?

**Comment by FDMatthias** [comment]
OP's topic of this issue has been solved and thus this issue will be closed. @sseyha Please follow issue #3 for your question.
