### ISSUE TITLE
How to change Navigationbar Title

### ISSUE THREAD

**Issue by TanNTAPlus** [appfoundry/react-native-multi-language-sample#3]
if I use 
```
static navigationOptions = ({ navigation }) => {
		return {
			title: I18n.t('home.about'),
		}
}
```
I can not change language of Title. How to change it?

**Comment by FDMatthias** [comment]
This is explained in the [tutorial](https://www.appfoundry.be/blog/2017/03/27/react-native-multi-language/#react-navigation-specific-code)/[readme](https://github.com/appfoundry/react-native-multi-language-sample#react-navigation-specific-code) (under the section 'React Navigation Specific Code').
