### ISSUE TITLE
No QRCode

### ISSUE THREAD

**Issue by keviin55** [appfoundry/react-native-multi-language-sample#4]
I cloned the sample project but it's not showing any QRcode after running it with npm and also yarn start. 

> node node_modules/react-native/local-cli/cli.js start
> Scanning 575 folders for symlinks in ...
>  Running packager on port 8081.                                            │ 
>  │                                                                            │ 
>  │  Keep this packager running while developing on any JS projects. Feel      │ 
>  │  free to close this tab and run your own packager instance if you          │ 
>  │  prefer.                                                                   │ 
>  │                                                                            │ 
>  │  https://github.com/facebook/react-native 
> 
> Looking for JS files in
>    /Use....
> 
> Loading dependency graph...
> React packager ready.

**Comment by FDMatthias** [comment]
I think you're expecting to see a QR code like with Expo / create-react-native-app? This sample was written before that was the standard.. So, there won't be any QR code shown, it's simply "react-native run-android" or "react-native run-ios".

I hope this answers your question?

**Comment by keviin55** [comment]
Thank you for the answer, with the simulator I am getting this error 
<img width="390" alt="screen shot 2017-10-11 at 10 33 13" src="https://user-images.githubusercontent.com/11744505/31429944-b2ad4b52-ae6f-11e7-9387-85d6458bb4ab.png">

**Comment by FDMatthias** [comment]
Have you tried the solution the error message contains? Replacing that piece of code?
If you can, please provide an example of the code triggering this error.

**Comment by keviin55** [comment]
The problem occur when I press "GO TO SETTINGS", this should be the code causing the problem:
```
Settings: {
    screen: SettingsContainer,
    navigationOptions: {
      title: (navigation) => {
        return navigation.state.params.title
      }
    }
  }

I tried to replace it but it didn't solve the problem.
```

**Comment by FDMatthias** [comment]
This seems like it's an issue with react-navigation and not with this project, as I can build and run it just fine. (Please have a look at https://github.com/react-community/react-navigation/issues/1733)

The code you provided is different than the code in the error. This makes me think something else, something react-navigation specific, is triggering the error. Or you adjusted the code which makes the error.

We're going to need more information/the actual code in order to help you.. but might I suggest creating an issue at the react-navigation repository?

**Comment by keviin55** [comment]
You are probably using another version of react-navigation. I think the problem is on the syntax of the code. With this code I do not get the error

```
Settings: {
    screen: SettingsContainer,
    navigationOptions: (navigation) => ({
      title: 'Login'
    })
  }
```

Do you have an idea on how to adapt it or shall I open an issue at react-navigation?

**Comment by keviin55** [comment]
This syntax solved the issue for me

```
Settings: {
  screen: SettingsContainer,
  navigationOptions: ({navigation}) => ({
    title: navigation.state.params.title
  })
}
```

**Comment by FDMatthias** [comment]
Okay, I'm glad you got it solved :) Maybe we'll update the project/blogpost to work with the latest versions of dependencies.. but that'll be something for when we have time for that. Pull-requests are encouraged!

Closing.
