### ISSUE TITLE
Header title translation

### ISSUE THREAD

**Issue by omar-bz** [appfoundry/react-native-multi-language-sample#9]
you claimed that we need to do extra work to translate title of the navigation bar.
but you can eliminate passing the title in the params if the I18n initialization is done before the creation of the nav routes(inside ../Containers/RootContainer.js) and pass them in the conf through navigationOptions object and that work for the rest of the app because nothing is loaded before the navigator.

**Comment by FDMatthias** [comment]
I'm not sure I follow. Could you elaborate a bit more? Where would you translate the titles? 

You can always do a pull request and I can have a look at it, if that is easier.

**Comment by FDMatthias** [comment]
Closed due to inactivity. Also, this would work for initial language translations, not for changing it afterwards (unless with a full reload of the app).
